/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const test_wasm: () => [number, number];
export const init_wasm: () => [number, number, number];
export const main: () => void;
export const __wbg_shieldingresult_free: (a: number, b: number) => void;
export const shieldingresult_proof: (a: number) => [number, number];
export const shieldingresult_commitment: (a: number) => [number, number];
export const shieldingresult_nullifier: (a: number) => [number, number];
export const __wbg_unshieldingresult_free: (a: number, b: number) => void;
export const unshieldingresult_proof: (a: number) => [number, number];
export const unshieldingresult_nullifier: (a: number) => [number, number];
export const __wbg_zkbridgecontext_free: (a: number, b: number) => void;
export const zkbridgecontext_new: (a: number) => [number, number, number];
export const zkbridgecontext_prove_shielding: (a: number, b: number, c: number, d: bigint, e: number, f: number, g: number, h: number) => [number, number, number];
export const zkbridgecontext_prove_unshielding: (a: number, b: number, c: number, d: bigint, e: number, f: number, g: number, h: number, i: number, j: number) => [number, number, number];
export const greet: (a: number, b: number) => [number, number];
export const add: (a: number, b: number) => number;
export const multiply: (a: number, b: number) => number;
export const get_version: () => [number, number];
export const get_build_info: () => [number, number, number];
export const async_greet: (a: number, b: number) => [number, number];
export const test_performance: () => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
